image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: test
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: root

before_script:
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  services:
    - mysql:5.7

  script:
    - apt-get update && apt-get install -y mysql-client
    - echo "SELECT 'Started';" | mysql --user=$MYSQL_USER --password="${MYSQL_ROOT_PASSWORD}" --host=$MYSQL_HOST "${MYSQL_DATABASE}"
    - mysql --host=$MYSQL_HOST --port=$MYSQL_PORT --user=$MYSQL_USER --password=$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE < MySqlSupplyCollectorTests/tests/data.sql 
    - echo "show tables;" | mysql --user=$MYSQL_USER --password="${MYSQL_ROOT_PASSWORD}" --host=$MYSQL_HOST "${MYSQL_DATABASE}"
    - dotnet build
    - dotnet test
