image: s2shape/s2shape-test-harness:latest

stages:
  - build
  - test

variables:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: test
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: root

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test

  services:
    - name: mysql:latest
      alias: mysql
      command: [ mysqld, --default-authentication-plugin=mysql_native_password, --skip-mysqlx]

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/MySqlSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init MySqlSupplyCollector "server=$MYSQL_HOST;Port=$MYSQL_PORT;uid=$MYSQL_USER;pwd=$MYSQL_ROOT_PASSWORD;database=$MYSQL_DATABASE;Connection Timeout=300"
    - dotnet SupplyCollectorDataLoader.dll -xunit MySqlSupplyCollector "server=$MYSQL_HOST;Port=$MYSQL_PORT;uid=$MYSQL_USER;pwd=$MYSQL_ROOT_PASSWORD;database=$MYSQL_DATABASE;Connection Timeout=300"
    - cd $ROOT_PROJECT_PATH
    - dotnet test

test5.7:
  stage: test

  services:
    - name: mysql:5.7.27
      alias: mysql

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/MySqlSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init MySqlSupplyCollector "server=$MYSQL_HOST;Port=$MYSQL_PORT;uid=$MYSQL_USER;pwd=$MYSQL_ROOT_PASSWORD;database=$MYSQL_DATABASE;Connection Timeout=300"
    - dotnet SupplyCollectorDataLoader.dll -xunit MySqlSupplyCollector "server=$MYSQL_HOST;Port=$MYSQL_PORT;uid=$MYSQL_USER;pwd=$MYSQL_ROOT_PASSWORD;database=$MYSQL_DATABASE;Connection Timeout=300"
    - cd $ROOT_PROJECT_PATH
    - dotnet test

load_test:
  stage: test
  services:
    - name: mysql:latest
      alias: mysql
      command: [ mysqld, --default-authentication-plugin=mysql_native_password, --skip-mysqlx]

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/MySqlSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init MySqlSupplyCollector "server=$MYSQL_HOST;Port=$MYSQL_PORT;uid=$MYSQL_USER;pwd=$MYSQL_ROOT_PASSWORD;database=$MYSQL_DATABASE;Connection Timeout=300"
    - dotnet SupplyCollectorDataLoader.dll -xunit MySqlSupplyCollector "server=$MYSQL_HOST;Port=$MYSQL_PORT;uid=$MYSQL_USER;pwd=$MYSQL_ROOT_PASSWORD;database=$MYSQL_DATABASE;Connection Timeout=300"
    - dotnet SupplyCollectorDataLoader.dll -samples MySqlSupplyCollector "server=$MYSQL_HOST;Port=$MYSQL_PORT;uid=$MYSQL_USER;pwd=$MYSQL_ROOT_PASSWORD;database=$MYSQL_DATABASE;Connection Timeout=300" TestCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 1000000
    - cd $ROOT_PROJECT_PATH/MySqlSupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness
